# Generated by Django 4.2.7 on 2023-11-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('seccion', models.CharField(max_length=30)),
                ('fecha_clase', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.IntegerField()),
                ('sexo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=30)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoMovil.profesores')),
            ],
        ),
        migrations.CreateModel(
            name='asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=100)),
                ('asistio', models.CharField(max_length=2)),
                ('clases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoMovil.clases')),
            ],
        ),
    ]
