# Generated by Django 4.2.7 on 2023-11-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoMovil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asistencias',
            table='asistencias',
        ),
        migrations.AlterModelTable(
            name='clases',
            table='clases',
        ),
        migrations.AlterModelTable(
            name='profesores',
            table='profesores',
        ),
        migrations.AlterModelTable(
            name='seccion',
            table='seccion',
        ),
    ]
