# Generated by Django 4.2.7 on 2023-11-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoMovil', '0005_alter_asistencias_clases_alter_clases_seccion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table=None,
        ),
        migrations.AlterModelTable(
            name='asistencias',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clases',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profesores',
            table=None,
        ),
        migrations.AlterModelTable(
            name='seccion',
            table=None,
        ),
    ]
