# Generated by Django 4.2.7 on 2023-11-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoMovil', '0007_alter_asistencias_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
    ]
