# Generated by Django 4.2.7 on 2023-11-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoMovil', '0010_clases_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
